print('Hello, world!')
person=input('What is your name?')
print('Hellow',person)
age=input('What is your age?')
print(age)
weight=input('what is your weight?')
print(weight)
height=input('what is your height?')
print(height)
